language: python
os: linux
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libav-tools libi2c-dev python-setuptools python-smbus
  - git clone git://git.drogon.net/wiringPi && cd ./wiringPi && ./build && cd ..
  - wget abyz.co.uk/rpi/pigpio/pigpio.zip && unzip pigpio.zip && cd ./PIGPIO && make -j4 && sudo make install && cd ..
  - pip install --upgrade pip webtest
install:
  - pip install --upgrade -r requirements.txt
virtualenv:
    system_site_packages: true
script:
  - cd mycodo && python -m pytest tests/software_tests/test_mycodo_flask/test_endpoints.py