language: python
python: 2.7
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libav-tools libffi-dev libi2c-dev python-dev python-setuptools python-smbus sqlite3
install:
  - pip install --upgrade -r requirements.txt