language: python
python: 2.7
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libav-tools libffi-dev libi2c-dev python-dev python-setuptools python-smbus sqlite3
  - pip install --upgrade setuptools ez_setup
  - cd && git clone git://git.drogon.net/wiringPi && cd ./wiringPi && ./build
  - cd & wget --quiet --show-progress -P $INSTALL_DIRECTORY/ abyz.co.uk/rpi/pigpio/pigpio.zip && unzip pigpio.zip && cd ./PIGPIO && make -j4 && make install
install:
  - pip install --upgrade -r requirements.txt