language: python
os: linux
dist: trusty
python:
  - 3.4
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libboost-python-dev gawk git libav-tools libffi-dev libi2c-dev nginx python3 python3-dev python3-numpy sqlite3 swig
  - git clone --recursive https://github.com/WiringPi/WiringPi-Python.git && cd WiringPi-Python && git submodule update --init && cd WiringPi && ./build && cd ../..
  - wget abyz.me.uk/rpi/pigpio/pigpio.tar && tar xf pigpio.tar && cd ./PIGPIO && make -j4 && sudo make install && cd ..
  - pip install --upgrade pip webtest
  - wget https://dl.influxdata.com/influxdb/releases/influxdb_1.6.0_amd64.deb && sudo dpkg -i influxdb_1.6.0_amd64.deb
  - sudo service influxdb start
  - influx -execute "CREATE DATABASE mycodo_db"
  - influx -database mycodo_db -execute "CREATE USER mycodo WITH PASSWORD 'mmdu77sj3nIoiajjs'"
install:
  - sed -i '/picamera/d' install/requirements.txt
  - pip3 install --upgrade -r install/requirements.txt
virtualenv:
    system_site_packages: true
script:
  - cd mycodo && python -m pytest tests/software_tests -s